pipeline {
    agent any

    environment {
        DOCKER_CREDENTIALS_ID = 'dockerhub-credentials' 
        DOCKER_IMAGE = 'jearod17/cicd-assessment'
        SONAR_TOKEN = credentials('sonar-token')
    }

    stages {
        stage('Checkout') {
            steps {
                echo '--- Clonando Repositorio ---'
                checkout scm
            }
        }

        stage('Test & Code Quality') {
            steps {
                echo '--- Ejecutando Tests y Análisis Estático ---'
                dir('app') {
                    // Crea entorno virtual para evitar error PEP 668
                    sh 'python3 -m venv venv'
                    sh 'venv/bin/pip install -r requirements.txt'
                    sh 'venv/bin/python -m xmlrunner test_app.py --output ../test-reports'
                }
            }
            post {
                always {
                    junit 'test-reports/*.xml'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                echo '--- Análisis con SonarQube ---'
                script {
                    def scannerHome = tool 'scanner'
                    
                    withSonarQubeEnv('SonarQube-Server') { 
                        sh "${scannerHome}/bin/sonar-scanner \
                            -Dsonar.projectKey=cicd-assessment \
                            -Dsonar.sources=app \
                            -Dsonar.host.url=http://sonarqube:9000 \
                            -Dsonar.login=${SONAR_TOKEN}"
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                echo '--- Construyendo Imagen Docker ---'
                script {
                    dockerImage = docker.build("${DOCKER_IMAGE}:${env.BUILD_NUMBER}", "-f pipeline/Dockerfile .")
                }
            }
        }

        stage('Security Scan (Trivy)') {
            steps {
                sh "trivy image --severity CRITICAL,HIGH --exit-code 0 ${DOCKER_IMAGE}:${env.BUILD_NUMBER}"
            }
        }

        stage('Push to DockerHub') {
            steps {
                echo '--- Subiendo imagen a DockerHub ---'
                script {
                    docker.withRegistry('', DOCKER_CREDENTIALS_ID) {
                        dockerImage.push()
                        dockerImage.push('latest')
                    }
                }
            }
        }
    }
}